// Module included in the following assemblies:
//
// * docs/cli-guide/master.adoc
// * docs/getting-started-guide/master.adoc
:env-gitlab:

:_content-type: CONCEPT
[id="conditional-b_{context}"]
= Conditional B

gitlab gitlab gitlab gitlab gitlab gitlab gitlab gitlab gitlab gitlab gitlab gitlab gitlab gitlab gitlab gitlab gitlab gitlab gitlab gitlab gitlab gitlab gitlab gitlab gitlab gitlab gitlab gitlab gitlab gitlab gitlab gitlab gitlab gitlab gitlab gitlab gitlab gitlab gitlab gitlab gitlab gitlab gitlab gitlab gitlab gitlab gitlab gitlab gitlab gitlab gitlab gitlab gitlab gitlab gitlab gitlab gitlab gitlab gitlab gitlab gitlab gitlab gitlab gitlab


The {CLIName} is a command-line tool in the {ProductName} that you can use to assess and prioritize migration and modernization efforts for applications. It provides numerous reports that highlight the analysis without using the other tools. The {CLIName} includes a wide array of customization options. By using the {CLIName}, you can tune {ProductShortName} analysis options or integrate with external automation tools.

ifndef::cli-guide[]
For more information about using the {CLIName}, see link:{ProductDocUserGuideURL}[_{UserCLIBookName}_].
endif::cli-guide[]

:!env-gitlab:
